version: '3'

services:
  node:
    image: node-api
    build: .
    restart: always
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    networks:
      - my-network
    volumes:
      - ./:/usr/app
  db:
    image: db-node-api
    build: ./db
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg-data:/var/lib/postgresql/data
    command: -p ${POSTGRES_PORT}
    networks:
      - my-network

volumes:
  pg-data:

networks:
  my-network:
